In [1]:
import torch

In [9]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

### Creating tensors


In [ ]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
MATRIX = torch.tensor([[7, 8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1].ndim

1

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR.ndim

3

### Random tensors

In [ ]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.3290, 0.4906, 0.9902, 0.2403],
        [0.6821, 0.2876, 0.7830, 0.5124],
        [0.3474, 0.7899, 0.4673, 0.3358]])

### Zeros and ones

In [ ]:
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

### Range of tensors

In [ ]:
one_to_ten = torch.arange(start=0, end=1000, step=77)
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [ ]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float32,
                               device=None,
                               requires_grad=False)
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

### Manipulating tensors

In [ ]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
tensor * 10

tensor([10, 20, 30])

In [ ]:
tensor - 10

tensor([-9, -8, -7])

### Matrix multiplication

In [ ]:
tensor * tensor

tensor([1, 4, 9])

In [ ]:
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
tensor_A = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]])

tensor_B = torch.tensor([[7, 8],
                        [9, 10],
                        [11, 12]])

tensor_B.T
# torch.mm(tensor_A, tensor_B.T)

tensor([[ 7,  9, 11],
        [ 8, 10, 12]])

### Min, max, mean, sum

In [ ]:
x = torch.rand(2, 2)
x, x.min(), x.mean(), x.sum(), x.argmin()

(tensor([[0.1742, 0.9147],
         [0.7975, 0.6256]]),
 tensor(0.1742),
 tensor(0.6280),
 tensor(2.5120),
 tensor(0))

### Reshaping

In [ ]:
x = torch.arange(1., 10.)
x, x.shape, x.reshape(1, 9), x.reshape(1, 9).shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 torch.Size([9]),
 tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([1, 9]))

In [ ]:
z = x.view(1, 9)
x_stacked = torch.stack([x, x, x], dim=0)
rand_tensor = torch.rand(3, 2, 2)
rand_tensor, rand_tensor.shape, rand_tensor.squeeze(), rand_tensor.squeeze().shape

(tensor([[[0.8777, 0.5270],
          [0.7893, 0.6182]],
 
         [[0.3526, 0.8761],
          [0.0542, 0.6877]],
 
         [[0.5487, 0.6036],
          [0.8199, 0.6574]]]),
 torch.Size([3, 2, 2]),
 tensor([[[0.8777, 0.5270],
          [0.7893, 0.6182]],
 
         [[0.3526, 0.8761],
          [0.0542, 0.6877]],
 
         [[0.5487, 0.6036],
          [0.8199, 0.6574]]]),
 torch.Size([3, 2, 2]))

In [ ]:
x_original = torch.rand(size=(224, 224, 3))
x_permuted = x_original.permute(2, 0, 1)
x_permuted

tensor([[[0.4774, 0.7727, 0.9767,  ..., 0.1151, 0.1976, 0.4591],
         [0.0023, 0.1904, 0.7106,  ..., 0.9494, 0.3664, 0.5222],
         [0.0084, 0.9752, 0.3832,  ..., 0.0929, 0.3702, 0.3167],
         ...,
         [0.8366, 0.7100, 0.8607,  ..., 0.3775, 0.7833, 0.5539],
         [0.5933, 0.3086, 0.3216,  ..., 0.4480, 0.8077, 0.4255],
         [0.1606, 0.6068, 0.3916,  ..., 0.4066, 0.1552, 0.8655]],

        [[0.8381, 0.3471, 0.1782,  ..., 0.8791, 0.0572, 0.6268],
         [0.0919, 0.3146, 0.0407,  ..., 0.0160, 0.1364, 0.0407],
         [0.0189, 0.6338, 0.6587,  ..., 0.9348, 0.3387, 0.1664],
         ...,
         [0.4992, 0.3593, 0.1915,  ..., 0.1465, 0.5714, 0.4926],
         [0.4436, 0.0357, 0.3390,  ..., 0.9422, 0.5061, 0.9089],
         [0.8507, 0.1763, 0.8063,  ..., 0.1558, 0.4435, 0.9063]],

        [[0.1774, 0.3414, 0.9246,  ..., 0.2673, 0.5510, 0.0379],
         [0.2418, 0.7817, 0.8074,  ..., 0.3697, 0.6588, 0.4995],
         [0.6622, 0.8069, 0.0125,  ..., 0.7764, 0.9973, 0.

### Indexing

In [ ]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x[0, 1, 1]

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 tensor(5))

### Numpy

In [ ]:
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
# tensor = torch.from_numpy(array).type(torch.float32)

array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
tensor = torch.ones(7)
numpy_tensor = torch.Tensor.numpy(tensor)
numpy_tensor

array([1., 1., 1., 1., 1., 1., 1.], dtype=float32)

### Random Seed - Reproducibility

In [ ]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_A = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A, random_tensor_B)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]]) tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])


In [ ]:
torch.cuda.is_available()

True

### GPU tensors

In [13]:
tensor = torch.tensor([1, 2, 3])

tensor_on_gpu = tensor.to(device)
print(tensor_on_gpu)
tensor_on_cpu = tensor_on_gpu.cpu().numpy()
print(tensor_on_cpu)

tensor([1, 2, 3], device='cuda:0')
[1 2 3]
